### ISSUE TITLE
searchProducts returns <h1>Software error:</h1>

### ISSUE THREAD

**Issue by M123-dev** [openfoodfacts/openfoodfacts-dart#165]
### Steps to reproduce:
(This is the config of the test: `api_searchProducts_test.dart`, name; "search products filter additives" )

``` dart
void main() async {
  const User TEST_USER = User(
    userId: 'openfoodfacts-dart',
    password: 'iloveflutter',
    comment: 'dart API test',
  );

  var parameters = <Parameter>[
    const OutputFormat(format: Format.JSON),
    const Page(page: 5),
    const PageSize(size: 10),
    const SearchSimple(active: true),
    const SortBy(option: SortOption.PRODUCT_NAME),
    const SearchTerms(terms: ['Fruit à coques']),
    const ContainsAdditives(filter: false)
  ];

  ProductSearchQueryConfiguration configuration =
      ProductSearchQueryConfiguration(
          parametersList: parameters,
          fields: [ProductField.ALL],
          language: OpenFoodFactsLanguage.FRENCH);

  SearchResult data = await OpenFoodAPIClient.searchProducts(
      TEST_USER, configuration,
      queryType: QueryType.TEST);

  print(data.products);
  print(data.count);
}
```

Returns: 
```
Unhandled exception:
FormatException: Unexpected character (at character 1)
<h1>Software error:</h1>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1271:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:936:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:506:36)
#5      JsonCodec.decode (dart:convert/json.dart:157:41)
#6      OpenFoodAPIClient.searchProducts (package:openfoodfacts/openfoodfacts.dart:187:45)
<asynchronous suspension>
#7      main (file:///D:/111Programming/Flutter/Projects/openfoodfacts-dart/fork/openfoodfacts-dart/example/lib/main.dart:162:23)
<asynchronous suspension>
```

Probably caused by some server side changes

**Comment by M123-dev** [comment]
Don't know what happend, but works again
