### ISSUE TITLE
Unhandled exception using OpenFoodAPIClient.searchProducts() with specific ProductSearchQueryConfiguration

### ISSUE THREAD

**Issue by christianfl** [openfoodfacts/openfoodfacts-dart#440]
**Describe the bug**
OpenFoodAPIClient.searchProducts() throws Unhandled Exception with a given ProductSearchQueryConfiguration. Occured searching for "**vitamin**".

**To Reproduce**

```
import 'package:openfoodfacts/model/UserAgent.dart';
import 'package:openfoodfacts/model/parameter/SearchTerms.dart';
import 'package:openfoodfacts/openfoodfacts.dart';
import 'package:openfoodfacts/utils/OpenFoodAPIConfiguration.dart';

var parameters = <Parameter>[
      const Page(page: 1),
      const PageSize(size: 10),
      const SortBy(option: SortOption.POPULARITY),
      SearchTerms(terms: ['vitamin']),
    ];

    ProductSearchQueryConfiguration configuration =
        ProductSearchQueryConfiguration(
            parametersList: parameters, language: OpenFoodFactsLanguage.GERMAN);

    SearchResult result =
        await OpenFoodAPIClient.searchProducts(null, configuration);
```

**Expected behavior**
result variable is filled with SearchResult without any unhandled exceptions.

**Screenshots**
If applicable, add screenshots to help explain your problem. Otherwise provide the error stacktraces:

```
E/flutter ( 7340): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'String?'
E/flutter ( 7340): #0      JsonHelper.imagesFromJson
package:openfoodfacts/utils/JsonHelper.dart:86
E/flutter ( 7340): #1      _$ProductFromJson
package:openfoodfacts/model/Product.g.dart:41
E/flutter ( 7340): #2      new Product.fromJson
package:openfoodfacts/model/Product.dart:417
E/flutter ( 7340): #3      _$SearchResultFromJson.<anonymous closure>
package:openfoodfacts/model/SearchResult.g.dart:15
E/flutter ( 7340): #4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
E/flutter ( 7340): #5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
E/flutter ( 7340): #6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:206:27)
E/flutter ( 7340): #7      new _GrowableList.of (dart:core-patch/growable_array.dart:153:28)
E/flutter ( 7340): #8      new List.of (dart:core-patch/array_patch.dart:51:28)
E/flutter ( 7340): #9      ListIterable.toList (dart:_internal/iterable.dart:213:44)
E/flutter ( 7340): #10     _$SearchResultFromJson
package:openfoodfacts/model/SearchResult.g.dart:16
E/flutter ( 7340): #11     new SearchResult.fromJson
package:openfoodfacts/model/SearchResult.dart:33
E/flutter ( 7340): #12     OpenFoodAPIClient.searchProducts
package:openfoodfacts/openfoodfacts.dart:313
E/flutter ( 7340): <asynchronous suspension>
E/flutter ( 7340): #13     OpenFoodFactsBinding.searchFood
package:energize/…/food_database_bindings/open_food_facts_binding.dart:64
E/flutter ( 7340): <asynchronous suspension>
```

**package information:**
Openfoodfacts package version: 1.14.0 (was already there in 1.12.0)

**Thanks in advance for any help!**

**Comment by M123-dev** [comment]
Probably can be fixed by a additional `.toString()` here https://github.com/openfoodfacts/openfoodfacts-dart/blob/ea79ad0f3283c50ba54e1767bcece5761c57f939/lib/utils/JsonHelper.dart#L86-L87

**Comment by M123-dev** [comment]
@christianfl a new release with the fix should be available any minute now 🎉

**Comment by christianfl** [comment]
@M123-dev Works flawless, thank you for the fast fix!
